//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleBooking()
        {
            this.EquipmentBookings = new HashSet<EquipmentBooking>();
        }
    
        public long VehicleBookingId { get; set; }
        public string Email { get; set; }
        public long VehicleId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public decimal TotalPrice { get; set; }
        public bool Collected { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentBooking> EquipmentBookings { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
